image:
  file: .gitpod.Dockerfile
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      echo "tasks - before"
      cp /workspace/f5-xc-tgw-ha/id_ed25519* ~/ || true
    init: |
      terragrunt run-all init
      echo "tasks - init"
    command: |
      echo "tasks - command"
      #  terragrunt run-all apply
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
